#!/bin/bash
sudo sshfs -o allow_other -o kernel_cache -o auto_cache -o reconnect -o compression=no -o cache_timeout=600 -o ServerAliveInterval=15 daniel.martin@hostel.ufabc.edu.br:public_html/ ~/www/
